image: illbilly/sfdx #image with sfdx installed

pipelines:
  default:
    - step:
        name: Build and tes
        script:
          - sfdx force:auth:jwt:grant --clientid 3MVG9er.T8KbeePRKRH4JnoMBFZPYvD0aglmscAwT77SSrsD1cPLZd19RjlDSev_En71d3xtUFY9rGIW.qL5O --jwtkeyfile $PRIVATE --username sanjaykumar2@deloitte.com.devreview --setalias dreamforce --instanceurl https://test.salesforce.com/
  tags:                         # add the 'tags' section
    release-*:                  # specify the tag
      - step:                   # define the build pipeline for the tag
          name: Build and release
          script:
            - npm install
            - npm test
            - npm run release
  branches:
    staging:
      - step:
          name: Clone
          script:
            - echo "Clone all the things!" 