image: illbilly/sfdx #image with sfdx installed

pipelines:
 branches:
    feature*:
     - step:
        script:
          - echo $SFDC_PROD_URL
          - echo $(sfdx --version)
          - sfdx force:auth:jwt:grant --clientid 3MVG9er.T8KbeePRKRH4JnoMBFZPYvD0aglmscAwT77SSrsD1cPLZd19RjlDSev_En71d3xtUFY9rGIW.qL5O --jwtkeyfile keys/server.key --username mdevaraju@deloitte.com.devreview --setalias dreamforce --instanceurl https://test.salesforce.com/
          - sfdx force:mdapi:retrieve -c -d src -w 20 -l RunLocalTests -u dreamforce
    master:
                - step:
                    script:
                      - echo $SFDC_PROD_URL
                                - echo $(sfdx --version)
                                - sfdx force:auth:jwt:grant --clientid 3MVG9er.T8KbeePRKRH4JnoMBFZPYvD0aglmscAwT77SSrsD1cPLZd19RjlDSev_En71d3xtUFY9rGIW.qL5O --jwtkeyfile keys/server.key --username mdevaraju@deloitte.com.devreview --setalias dreamforce --instanceurl https://test.salesforce.com/
                                - sfdx force:mdapi:retrieve -c -d src -w 20 -l RunLocalTests -u dreamforce